nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./:/web/
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    build: ./docker/php
    volumes:
        - ./:/web/
        - ./docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini